export const REQUEST_SEARCH_HISTORY = "REQUEST_SEARCH_HISTORY";
export const REQUEST_SEARCH_RESULT = "REQUEST_SEARCH_RESULT";

export const FAILED_SEARCH_HISTORY = "FAILED_SEARCH_HISTORY";
export const FAILED_SEARCH_RESULT = "FAILED_SEARCH_RESULT";

export const SUCCESS_SEARCH_HISTORY = "SUCCESS_SEARCH_HISTORY";
export const SUCCESS_SEARCH_RESULT = "SUCCESS_SEARCH_RESULT";

export const CLEAR_SEARCH = "CLEAR_SEARCH";

export const SUCCESS_SEARCH_HISTORY_STORAGE = "SUCCESS_SEARCH_HISTORY_STORAGE";
